### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by Daru00** [haven1433/HexManiacAdvance#190]
Well i wanted to test this tool but it doesn't work no matter what i do.
Installed the suspicious requirement,after that i double click and it won't launch no matter how many times i launch it.
I use windows 7 (no won't update to windows 10 because i don't want spyware or NSA tools on my OS) linux version won't work on ubuntu so out of ideas.
COuld have used something like this but is just like advanca text editor that doesn't edit anything in reality.
I just need something that runs on default without requiring extra downloads using either java or VC

**Comment by haven1433** [comment]
As mentioned in the ReadMe, HMA requires [.Net 6.0 Desktop](https://github.com/haven1433/HexManiacAdvance#getting-started). That's available to install on Windows 7 with the latest service pack, but that service pack is no longer available through Microsoft since Windows 7 ended support in January of 2020.

If you don't want to install the requirements, you won't be able to run the program. I'm sorry you find them suspicious, but .Net has been publicly available since 2021 and is used by thousands of programs, and is considered safe by the community. HMA itself is open source, so you can see in the code that no data is being collected by the program, except for crash logs which are only logged to disk and never uploaded unless you post them somewhere manually.

If you don't trust the requirements, then you're welcome to edit the software to replace or remove them.

**Comment by Daru00** [comment]
i do have the requirements thing is it won't open no matter what,not even clicking over 60 times to launch it will do something.
and is suspicious the link it gives (kinda weird since i have an updated version of net desktop so it should run without issues and shouldn't tell me to downgrade on my other PC)
What i did on second PC (disconnected from internet)
>install the downloaded file
>click over 60 times to launch it
>nothing happens
>doesn't show up in task manager not even a second
>direct X,drivers,updates,VC++,java, net framework everything is in order.
>normal PC it asks me to downgrade the net desktop version since i don't have it installed  according to hexmaniac.

**Comment by haven1433** [comment]
My only suggestions are:
(1) run `dotnet --info` from a command line to make sure you have dotnet desktop 6installed. The output should look something like:

```
.NET runtimes installed:
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Or (2) Join the discord server and maybe someone can help you with your setup to get the program running. There are hundreds of members who are able to run it, so it's more likely some issue with your dependencies than an issue with the program.

**Comment by Daru00** [comment]
i will simply use my old XP machine and advance text since this doesn't work.
THis is the one i had on the disconnected machine and currently installed on my primary PC
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Sadly it says "you need XXXX runtime" so even following instructions and uninstalling the most recent in favor of the one i had to grab from the link still didn't work as i explained.
>Oflline PC Intel Pentium D 2.8 GHz,2GB ram,Amd Radeon Sapphyre HD 1 GB, Windows 7 SP1 all updates,all VC++,directX9 updated (doesn't work and had to downgrade the net desktop version)
>Online PC higher specs same settings and install,won't detect net desktop version.
I wanted to use a tool to edit fire red text but sadly this doesn't even run VC++ or quicktime would be a better and more compatible choice to build

**Comment by haven1433** [comment]
The page you links has multiple dotnet installs, which is why I keep specifying that you want the "desktop" version:

![image](https://github.com/haven1433/HexManiacAdvance/assets/10834600/d3e6f870-f407-4499-939c-f900bc9e3235)

> Windows 7 SP1

Supposedly .Net 6 [does work on Windows 7 SP1 ESU](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70), but .Net 7 and beyond do not. There are [older versions of HMA](https://github.com/haven1433/HexManiacAdvance/releases/tag/v0.4.3) that run using .Net Framework 4.X, but that won't have all the latest features you'll see in tutorials. As usual, my recommendation matches that of Microsoft: Windows 7 is out of service, you should consider using a more recent operating system.
