### ISSUE TITLE
data corruption in Pokemon Emerald

### ISSUE THREAD

**Issue by Ravendeth** [haven1433/HexManiacAdvance#197]
Getting random after-battle crashes in Pokemon Emerald after I make any patch that does any of the following:
1. Edit too many Pokemon types or palettes in one patch.
2. Change too many Pokemons' learnable TMs or tutor moves in one patch.
3. Edit the map Route 124 or any adjacent maps or their fishing wild data in one patch.

The versions before I used HMA are all fine, but even if I try to recreate individual edits from patch history notes, I end up with a slightly different broken ROM each time in the end.
It even breaks additional data patches like the Day/Night System inserted into free data much later in the free space.

In some cases the wild Pokemon I'm seeing in HMA's editor and in-game are entirely different entities.

blue electric-type skitty (non-shiny) in editor
![Clipboard02](https://github.com/haven1433/HexManiacAdvance/assets/115993813/2affd2a0-a841-4fcb-899c-4186b1ec7b8f)

purple psychic-type skitty (non-shiny) in-game
![Clipboard01](https://github.com/haven1433/HexManiacAdvance/assets/115993813/f623b2b2-3e27-42f1-b1bc-df5aa6557bfa)

My best guess for the cause is improper (not actually blank) offsets being used, like what AdvanceMap does.  

Maybe it's just me trying to finish a jank old project, but I just wanted to get my issue out there in case it helps somebody else avoid data corruption.

**Comment by haven1433** [comment]
> recreate individual edits from patch history notes, I end up with a slightly different broken ROM each time in the end.

This seems really concerning... making the same edit multiple times should definitely result in the same change. Since I don't have access to your rom/changes, we'll need to find a way to debug this using a vanilla (unedited) copy of Emerald.

Starting from a clean Emerald gba rom, do you have steps that reliably cause HMA to corrupt your rom? A particular pokemon type you can change that then shows via diff that it changed more than expected?

**Comment by haven1433** [comment]
Closing for lack of communication
