### ISSUE TITLE
Issues scripting

### ISSUE THREAD

**Issue by Coneruu** [haven1433/HexManiacAdvance#212]
Scripting is fine in npcs, but when used in actual script blocks the game locks the player (no matter if lock / lockall is used) and the player is unable to move. how do i fix it?

**Comment by Coneruu** [comment]
{it freezes the game not just locking the player}

**Comment by haven1433** [comment]
Have you read the [HMA Scripting Tutorials](https://github.com/haven1433/HexManiacAdvance/wiki/Everything-You-Need-for-Event-Scripting-in-HexManiacAdvance)? Specifically the one about [script events](https://github.com/haven1433/HexManiacAdvance/wiki/Overworld-Scripting-%E2%80%90-Script-Events) that talks about setting up script triggers?

**Comment by ShinyTillDawn** [comment]
This is not a bug with Hex Maniac Advance at all. Variable 0000 (in your `Trigger` field) is not a valid variable to use for script tiles, which is why the client freezes upon stepping on the tile. You must choose a [valid variable number](https://github.com/haven1433/HexManiacAdvance/wiki/Overworld-Scripting-%E2%80%90-Variables) before proceeding.
