### ISSUE TITLE
Adding Fourth Starter

### ISSUE THREAD

**Issue by Tyrranux** [haven1433/HexManiacAdvance#227]
Where exactly does this program expect me to go to "change coordinates to multiple of 4"?

**Comment by Tyrranux** [comment]
That's what the pop up told me when I dragged and dropped the "Emerald_ExpandStarters.hma" into the program, yet when I was taken to the Starter Edit page I still only see three options to edit. Now I got an inaccessible Pokeball graphic sitting there at the top corner of the Starter Select screen. So how far into the raw hexadecimal do I have to dive into this time?

**Comment by Tyrranux** [comment]
I dunno why I even bother....

**Comment by Axcellerator** [comment]
Haven has been extremely busy this past few days so it's hard for him to answer, you can join the discord server that has a lot more people available for support

**Comment by Tyrranux** [comment]
I can't even use Discord, that site got pissy at me for even signing up and banned me from service just for the "crime" of having my VPN turned on at the time. Fucking site won't even let me make any posts it's that much of an entitled BRAT of a website! Overall that's a dead end for me.

You might have well just said I'm on my own which has just been the typical status quo since I even started this project I'm doing. I have no money to pay others to help me code or play test this thing. Often when I ask for help I only get either days of dead silence or the brush off by way of "welcome to the rom hack community" or "that's rough buddy" or "you should be going here for help" comments. One of the few that did help on Youtube was apparently pissed I asked in the "wrong place" like I'm just suppose to know the right procedure for asking help. 

I would greatly appreciate if maybe you can just give me some help instead of Hexen. I just tried some desperate strongarming method that barely works, still only three Pokeballs on screen but I can select a fourth starter, I don't know if I just fucked things up royal in the long run.....

**Comment by Axcellerator** [comment]
lemme look into it a bit cause I've never done this before, I assume you're using the HMA script for expanding starters in emerald right?

**Comment by Tyrranux** [comment]
Y'know what? Nevermind.

**Comment by haven1433** [comment]
After running the script, I was presented with:

![image](https://github.com/user-attachments/assets/0ee870a7-5396-4d3a-b140-85e352db2b62)

The note in the script said "pokeball coordinates must be a multiple of four" so that'll be talking about the values listed for 'x' and 'y' on the left side, labeled `scripts.newgame.starters.pokeballs`.

You can get back to this screen by typing something like "starter pokemon" in the goto menu:

![image](https://github.com/user-attachments/assets/0de9180b-3898-48e7-a386-140e0a8955ba)

Sorry you weren't able to figure this out, but I'm not sure what I can do to make the directions or interface more clear. As was previously said, I don't personally have time to check GitHub and Discord for this project consistently anymore. But there are thousands of users on Discord that can help with this issue. I suggest you take up your discord issues with discord, because ranting about it here will do you no good.

**Comment by Tyrranux** [comment]
Discord is useless to me. It got so pissy about me using a VPN it
immediately blocked my account the nanoclic I made one. And even after I
could access it, the piece of shit refuses to let me join any "servers" or
post anything. I can't do anything there! Can't contact anybody, can't join
any groups! You might as well have told me I'm shit out of luck and no one
is gonna help me given how much of a literal dead end that website is! Just
like with Reddit and Twitter I get punished for paying 99 dollars a year
for Surfshark because God forbid I have a VPN!

Not that it matters now since I'm canceling my hack, I got nowhere to post
it so others can try it. Even after I got it as an IPS Patch like those
entitled cunts at Pokemoncommunity wanted they still refuse to even give my
post the go ahead so it can be viewed publicly. And I can't get a damn
reply back from that stupid PokemCoders.com on how I can even share a
measly demo, for all I know there is no one at the help desk. So what's the
point? I can't get it to my fans on Deviantart without charging them money,
I got no options! And I know you are gonna deny me the option to post
anything on your wiki because you clearly hate my guts. Well that's fine,
the feeling's mutual.
