### ISSUE TITLE
DLL being flagged for malware

### ISSUE THREAD

**Issue by DeathDoors** [haven1433/HexManiacAdvance#228]
![Screenshot](https://github.com/user-attachments/assets/d8fcbb8e-945c-4f0a-84f6-d280fd9754f1)

I Know its most likely a false positive, just wanted to draw it to your attention.

**Comment by whamer100** [comment]
One hit is basically not much of a worry (especially for an AI Heuristic hit, as this scan resulted in)

**Comment by haven1433** [comment]
Yup, not much I can do about it unless I want to pay for a digital cert. If you're wanting to be extra safe, you're welcome to examine the source code for anything malicious and build it yourself using Visual Studio. Otherwise, all I can provide is my guarantee that I've put nothing malicious in the software. It'll check running processes (using a named pipe) to see if there's another instance of HMA open, it'll check data from the internet to see if there's a new HMA version available. Those are probably the two fishiest things it does.
