### ISSUE TITLE
Works only with Windows 10 1607 and newer

### ISSUE THREAD

**Issue by TomaszA2** [haven1433/HexManiacAdvance#74]
Though I am not on Windows 7, 8, nor any older, my Windows 10 hadn't been updated for a very long time, which with my bandwidth would take another few weeks at this point.
Therefore I ask, is .Net 4.7.2 really a must have or could you simply change it in project settings to any lower and compile with no trouble?

It's quite strange because Windows 7 is capable of installing newest dotnets, while all of Windows 8 and some versions of 10 are not allowed. For Windows 8 newest installable is 4.6.1. For my Windows 10 it is 4.6.2.
Now I also see that Windows 8.1 is again allowed to install everything that Windows 7 was able to.

Thank you for any answer. Tool seems to be interesting but I didn't get a chance to use it yet.

**Comment by haven1433** [comment]
There's code in the project that uses newer features of C# / .Net, so downgrading to 4.6.1 or 4.6.2 is not so simple as toggling a config setting. As such, I don't intend to downgrade what version of .Net is used for the project, and actually plan to update to .Net 5 later this year. .Net 5 has the same requirements as .Net 4.7.2.

Sounds like you're using a version of Windows prior to the Windows 10 Anniversary Update (version 1607), since that's the first version that supports .Net 4.7 and above. That version has been available since August 2, 2016, and should be a free update for Windows 10 users.
