### ISSUE TITLE
[Feature Request] Word wrap for the Text tab of the Content box

### ISSUE THREAD

**Issue by LOuroboros** [haven1433/HexManiacAdvance#75]
Title.

It would be nice if HMA could allow the user to enable Word Wrap as an option to visualize text. The feature itself is commonly present in text editors and it makes it so all the text is presented in a vertical format instead of going full horizontal.

Ex:
![NewOptIllustration](https://user-images.githubusercontent.com/4485172/112643742-97bf2300-8e3c-11eb-88b9-a2ccc821a0d1.png)

I'm aware the size of the box can be modified by the user at will by resizing it from its corners, but I like the default size and having to constantly expand it back and forth would probably get quite annoying, which is what led me to suggest the feature.
It'd make easier to read text strings from within HMA, imo.

**Comment by haven1433** [comment]
Since the line-end characters are included in the string, the line wraps you see in HMA are completely arbitrary. The intent was to _not_ auto-wrap, except on line-end characters, so that you can see when your text is too wide to fit in a textbox. The fontsize default width are such that if you've become too wide to see it, you probably are too wide for the game.

... but looking at your example, it seems like it auto-wraps on \n (0xFE) and \pn (0xFB), but not on \l (0xFA). If I fix that, then your example would look like:
\CC0303\CC0104BLAKE: Non accetto il vostro\n
rifiuto, con o senza il vostro\pn
consenso, il progetto verra\l
avviato, ora tutti in postazione.\l
\CC0301\CC0108OAK: Blake, tu sei folle, vuoi\l
far esplodere tutto quanto?\l
\CC0303\CC0104BLAKE: L'unica cosa che potrebbe\l
accadere e che il reattore\l
centrale si spenga a causa della\l
poca energia immagazzinata.\l
Non voglio continuare a discutere,\l
se non ubbidite dovro prendere dei\l
seri provvedimenti, e chiaro?

It seems that if I wrap on \l, the line length is much more reasonable. I'll definitely do that. Aside from that, resetting the left panel to the default size can be done by double-clicking the divider.

Is that sufficient? Or are there still situations where having a line wrap would be useful?

**Comment by LOuroboros** [comment]
> 
> 
> Since the line-end characters are included in the string, the line wraps you see in HMA are completely arbitrary. The intent was to _not_ auto-wrap, except on line-end characters, so that you can see when your text is too wide to fit in a textbox. The fontsize default width are such that if you've become too wide to see it, you probably are too wide for the game.
> 
> ... but looking at your example, it seems like it auto-wraps on \n (0xFE) and \pn (0xFB), but not on \l (0xFA). If I fix that, then your example would look like:
> \CC0303\CC0104BLAKE: Non accetto il vostro\n
> rifiuto, con o senza il vostro\pn
> consenso, il progetto verra\l
> avviato, ora tutti in postazione.\l
> \CC0301\CC0108OAK: Blake, tu sei folle, vuoi\l
> far esplodere tutto quanto?\l
> \CC0303\CC0104BLAKE: L'unica cosa che potrebbe\l
> accadere e che il reattore\l
> centrale si spenga a causa della\l
> poca energia immagazzinata.\l
> Non voglio continuare a discutere,\l
> se non ubbidite dovro prendere dei\l
> seri provvedimenti, e chiaro?
> 
> It seems that if I wrap on \l, the line length is much more reasonable. I'll definitely do that. Aside from that, resetting the left panel to the default size can be done by double-clicking the divider.
> 
> Is that sufficient? Or are there still situations where having a line wrap would be useful?

That sounds good to me, yeah.

**Comment by haven1433** [comment]
This is now fixed in the master branch and will be in the next release.
