### ISSUE TITLE
Move Expandable Issue

### ISSUE THREAD

**Issue by holykaito** [haven1433/HexManiacAdvance#81]
After using the **Make Move Expandable**, moves always miss when used, even though they have a 100% acc rate.

**Comment by haven1433** [comment]
There was some bugs in move expansion in the latest release which are fixed in the current source. What version were you using to see this bug?

**Comment by haven1433** [comment]
No response from OP in over a week. Closing due to lack of information / communication.

**Comment by holykaito** [comment]
I am using version 0.4.2. Is it the latest version?

**Comment by haven1433** [comment]
The latest release is 0.4.3, but there have been bug fixes to HMA's move expansion routine since then. You can build an updated version from source, or download an expiremental release with the latest changes from Discord. Or you can wait a bit longer until 0.4.4, which should have those fixes. But that may be a little while.
